"""create phase 1 core domain

Revision ID: 0002_phase_1_core_domain
Revises: 0001_phase_0_baseline
Create Date: 2026-08-30 14:28:50.862957
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0002_phase_1_core_domain"
down_revision: str | None = "0001_phase_0_baseline"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "inactive",
                name="taxonomy_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_categories")),
        sa.UniqueConstraint("name", name=op.f("uq_categories_name")),
        sa.UniqueConstraint("slug", name=op.f("uq_categories_slug")),
    )
    op.create_index(op.f("ix_categories_sort_order"), "categories", ["sort_order"], unique=False)
    op.create_table(
        "entities",
        sa.Column(
            "type",
            sa.Enum(
                "person",
                "organization",
                "sports_team",
                "movie",
                "tv_show",
                "game",
                "artist",
                "venue",
                "event",
                "brand",
                "franchise",
                "location",
                "other",
                name="entity_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("canonical_name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=180), nullable=False),
        sa.Column("aliases", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("external_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_entities")),
        sa.UniqueConstraint("slug", name=op.f("uq_entities_slug")),
    )
    op.create_index(
        "ix_entities_aliases_gin", "entities", ["aliases"], unique=False, postgresql_using="gin"
    )
    op.create_index(
        "ix_entities_external_ids_gin",
        "entities",
        ["external_ids"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(op.f("ix_entities_type"), "entities", ["type"], unique=False)
    op.create_table(
        "geography_nodes",
        sa.Column(
            "type",
            sa.Enum(
                "world",
                "country",
                "state_or_province",
                "metro",
                "city",
                "district",
                name="geography_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=160), nullable=False),
        sa.Column("country_code", sa.String(length=2), nullable=True),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("timezone", sa.String(length=64), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["geography_nodes.id"],
            name=op.f("fk_geography_nodes_parent_id_geography_nodes"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_geography_nodes")),
        sa.UniqueConstraint("slug", name=op.f("uq_geography_nodes_slug")),
    )
    op.create_index(
        op.f("ix_geography_nodes_country_code"), "geography_nodes", ["country_code"], unique=False
    )
    op.create_index(
        op.f("ix_geography_nodes_parent_id"), "geography_nodes", ["parent_id"], unique=False
    )
    op.create_table(
        "sources",
        sa.Column("external_id", sa.String(length=255), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=180), nullable=False),
        sa.Column("canonical_url", sa.Text(), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sources")),
        sa.UniqueConstraint("external_id", name=op.f("uq_sources_external_id")),
        sa.UniqueConstraint("slug", name=op.f("uq_sources_slug")),
    )
    op.create_table(
        "topics",
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("slug", sa.String(length=160), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "inactive",
                name="taxonomy_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_topics")),
        sa.UniqueConstraint("name", name=op.f("uq_topics_name")),
        sa.UniqueConstraint("slug", name=op.f("uq_topics_slug")),
    )
    op.create_table(
        "content_items",
        sa.Column("external_id", sa.String(length=255), nullable=True),
        sa.Column(
            "content_type",
            sa.Enum(
                "article",
                "image",
                "gallery",
                "meme",
                "video",
                "short",
                "live",
                "event",
                name="content_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "received",
                "processing",
                "ready",
                "scheduled",
                "published",
                "unpublished",
                "retracted",
                "archived",
                "deleted",
                "failed",
                name="content_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.Column("original_url", sa.Text(), nullable=True),
        sa.Column("original_language", sa.String(length=35), nullable=False),
        sa.Column("primary_language", sa.String(length=35), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("subtitle", sa.String(length=500), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("publication_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("original_publication_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("canonical_content_hash", sa.String(length=64), nullable=True),
        sa.Column("story_cluster_id", sa.String(length=255), nullable=True),
        sa.Column("author", sa.String(length=255), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("seo", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
            name=op.f("fk_content_items_source_id_sources"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_content_items")),
    )
    op.create_index(
        op.f("ix_content_items_canonical_content_hash"),
        "content_items",
        ["canonical_content_hash"],
        unique=False,
    )
    op.create_index("ix_content_items_external_id", "content_items", ["external_id"], unique=False)
    op.create_index("ix_content_items_source_id", "content_items", ["source_id"], unique=False)
    op.create_index(
        "ix_content_items_status_publication_time",
        "content_items",
        ["status", "publication_time"],
        unique=False,
    )
    op.create_index(
        "ix_content_items_story_cluster_id", "content_items", ["story_cluster_id"], unique=False
    )
    op.create_table(
        "portals",
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("domain", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "active",
                "inactive",
                name="portal_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("primary_geography_id", sa.Uuid(), nullable=True),
        sa.Column("default_language", sa.String(length=35), nullable=False),
        sa.Column("supported_languages", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("branding", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("logo", sa.Text(), nullable=True),
        sa.Column("category_settings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("ranking_settings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("ai_settings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("advertising_settings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("seo_settings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("feature_flags", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["primary_geography_id"],
            ["geography_nodes.id"],
            name=op.f("fk_portals_primary_geography_id_geography_nodes"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_portals")),
        sa.UniqueConstraint("domain", name=op.f("uq_portals_domain")),
        sa.UniqueConstraint("slug", name=op.f("uq_portals_slug")),
    )
    op.create_index(
        op.f("ix_portals_primary_geography_id"), "portals", ["primary_geography_id"], unique=False
    )
    op.create_table(
        "content_categories",
        sa.Column("content_item_id", sa.Uuid(), nullable=False),
        sa.Column("category_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("fk_content_categories_category_id_categories"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["content_item_id"],
            ["content_items.id"],
            name=op.f("fk_content_categories_content_item_id_content_items"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "content_item_id", "category_id", name=op.f("pk_content_categories")
        ),
    )
    op.create_index(
        "ix_content_categories_category_id", "content_categories", ["category_id"], unique=False
    )
    op.create_table(
        "content_entities",
        sa.Column("content_item_id", sa.Uuid(), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("relationship_type", sa.String(length=64), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("source", sa.String(length=120), nullable=True),
        sa.CheckConstraint(
            "confidence IS NULL OR (confidence >= 0 AND confidence <= 1)",
            name=op.f("ck_content_entities_confidence_range"),
        ),
        sa.ForeignKeyConstraint(
            ["content_item_id"],
            ["content_items.id"],
            name=op.f("fk_content_entities_content_item_id_content_items"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["entities.id"],
            name=op.f("fk_content_entities_entity_id_entities"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("content_item_id", "entity_id", name=op.f("pk_content_entities")),
    )
    op.create_index(
        "ix_content_entities_entity_id", "content_entities", ["entity_id"], unique=False
    )
    op.create_table(
        "content_geographies",
        sa.Column("content_item_id", sa.Uuid(), nullable=False),
        sa.Column("geography_id", sa.Uuid(), nullable=False),
        sa.Column(
            "relationship_type",
            sa.Enum(
                "primary",
                "mentioned",
                "event_location",
                "person_origin",
                "team_location",
                "venue_location",
                name="content_geography_relationship",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("confidence", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("source", sa.String(length=120), nullable=True),
        sa.CheckConstraint(
            "confidence IS NULL OR (confidence >= 0 AND confidence <= 1)",
            name=op.f("ck_content_geographies_confidence_range"),
        ),
        sa.ForeignKeyConstraint(
            ["content_item_id"],
            ["content_items.id"],
            name=op.f("fk_content_geographies_content_item_id_content_items"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["geography_id"],
            ["geography_nodes.id"],
            name=op.f("fk_content_geographies_geography_id_geography_nodes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "content_item_id",
            "geography_id",
            "relationship_type",
            name=op.f("pk_content_geographies"),
        ),
    )
    op.create_index(
        "ix_content_geographies_geography_id", "content_geographies", ["geography_id"], unique=False
    )
    op.create_table(
        "content_topics",
        sa.Column("content_item_id", sa.Uuid(), nullable=False),
        sa.Column("topic_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["content_item_id"],
            ["content_items.id"],
            name=op.f("fk_content_topics_content_item_id_content_items"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["topic_id"],
            ["topics.id"],
            name=op.f("fk_content_topics_topic_id_topics"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("content_item_id", "topic_id", name=op.f("pk_content_topics")),
    )
    op.create_index("ix_content_topics_topic_id", "content_topics", ["topic_id"], unique=False)
    op.create_table(
        "content_versions",
        sa.Column("content_item_id", sa.Uuid(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("source_revision", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("change_reason", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "source_revision IS NULL OR source_revision > 0",
            name=op.f("ck_content_versions_source_revision_positive"),
        ),
        sa.CheckConstraint(
            "version_number > 0", name=op.f("ck_content_versions_version_number_positive")
        ),
        sa.ForeignKeyConstraint(
            ["content_item_id"],
            ["content_items.id"],
            name=op.f("fk_content_versions_content_item_id_content_items"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_content_versions")),
        sa.UniqueConstraint(
            "content_item_id", "version_number", name="uq_content_versions_item_version"
        ),
    )
    op.create_index(
        "ix_content_versions_content_item_id", "content_versions", ["content_item_id"], unique=False
    )
    op.create_table(
        "media_assets",
        sa.Column("content_item_id", sa.Uuid(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "image",
                "video",
                "audio",
                "thumbnail",
                "poster",
                "document",
                name="media_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("storage_url", sa.Text(), nullable=True),
        sa.Column("mime_type", sa.String(length=255), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("duration", sa.Numeric(precision=12, scale=3), nullable=True),
        sa.Column("size", sa.BigInteger(), nullable=True),
        sa.Column("checksum", sa.String(length=128), nullable=True),
        sa.Column("copyright", sa.Text(), nullable=True),
        sa.Column("attribution", sa.Text(), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "ready",
                "failed",
                "inactive",
                name="media_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "duration IS NULL OR duration >= 0", name=op.f("ck_media_assets_duration_nonnegative")
        ),
        sa.CheckConstraint(
            "height IS NULL OR height >= 0", name=op.f("ck_media_assets_height_nonnegative")
        ),
        sa.CheckConstraint(
            "size IS NULL OR size >= 0", name=op.f("ck_media_assets_size_nonnegative")
        ),
        sa.CheckConstraint(
            "width IS NULL OR width >= 0", name=op.f("ck_media_assets_width_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["content_item_id"],
            ["content_items.id"],
            name=op.f("fk_media_assets_content_item_id_content_items"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_media_assets")),
    )
    op.create_index(op.f("ix_media_assets_checksum"), "media_assets", ["checksum"], unique=False)
    op.create_index(
        op.f("ix_media_assets_content_item_id"), "media_assets", ["content_item_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_media_assets_content_item_id"), table_name="media_assets")
    op.drop_index(op.f("ix_media_assets_checksum"), table_name="media_assets")
    op.drop_table("media_assets")
    op.drop_index("ix_content_versions_content_item_id", table_name="content_versions")
    op.drop_table("content_versions")
    op.drop_index("ix_content_topics_topic_id", table_name="content_topics")
    op.drop_table("content_topics")
    op.drop_index("ix_content_geographies_geography_id", table_name="content_geographies")
    op.drop_table("content_geographies")
    op.drop_index("ix_content_entities_entity_id", table_name="content_entities")
    op.drop_table("content_entities")
    op.drop_index("ix_content_categories_category_id", table_name="content_categories")
    op.drop_table("content_categories")
    op.drop_index(op.f("ix_portals_primary_geography_id"), table_name="portals")
    op.drop_table("portals")
    op.drop_index("ix_content_items_story_cluster_id", table_name="content_items")
    op.drop_index("ix_content_items_status_publication_time", table_name="content_items")
    op.drop_index("ix_content_items_source_id", table_name="content_items")
    op.drop_index("ix_content_items_external_id", table_name="content_items")
    op.drop_index(op.f("ix_content_items_canonical_content_hash"), table_name="content_items")
    op.drop_table("content_items")
    op.drop_table("topics")
    op.drop_table("sources")
    op.drop_index(op.f("ix_geography_nodes_parent_id"), table_name="geography_nodes")
    op.drop_index(op.f("ix_geography_nodes_country_code"), table_name="geography_nodes")
    op.drop_table("geography_nodes")
    op.drop_index(op.f("ix_entities_type"), table_name="entities")
    op.drop_index("ix_entities_external_ids_gin", table_name="entities", postgresql_using="gin")
    op.drop_index("ix_entities_aliases_gin", table_name="entities", postgresql_using="gin")
    op.drop_table("entities")
    op.drop_index(op.f("ix_categories_sort_order"), table_name="categories")
    op.drop_table("categories")
    # ### end Alembic commands ###
