"""implement phase 2 integrator ingestion

Revision ID: 0003_phase_2_ingestion
Revises: 0002_phase_1_core_domain
Create Date: 2026-08-30 15:22:27.786755
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0003_phase_2_ingestion"
down_revision: str | None = "0002_phase_1_core_domain"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "integrator_connections",
        sa.Column("instance_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("active_key_id", sa.String(length=64), nullable=False),
        sa.Column("active_secret", sa.Text(), nullable=False),
        sa.Column("previous_key_id", sa.String(length=64), nullable=True),
        sa.Column("previous_secret", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "previous_key_id IS NULL OR previous_key_id <> active_key_id",
            name=op.f("ck_integrator_connections_distinct_signing_key_ids"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_integrator_connections")),
    )
    op.create_index(
        op.f("ix_integrator_connections_instance_id"),
        "integrator_connections",
        ["instance_id"],
        unique=True,
    )
    op.create_table(
        "incoming_packages",
        sa.Column("package_id", sa.Uuid(), nullable=False),
        sa.Column("integrator_connection_id", sa.Uuid(), nullable=False),
        sa.Column("content_item_id", sa.Uuid(), nullable=True),
        sa.Column("latest_version", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "latest_version > 0", name=op.f("ck_incoming_packages_latest_version_positive")
        ),
        sa.ForeignKeyConstraint(
            ["content_item_id"],
            ["content_items.id"],
            name=op.f("fk_incoming_packages_content_item_id_content_items"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["integrator_connection_id"],
            ["integrator_connections.id"],
            name=op.f("fk_incoming_packages_integrator_connection_id_integrator_connections"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_incoming_packages")),
        sa.UniqueConstraint("content_item_id", name=op.f("uq_incoming_packages_content_item_id")),
        sa.UniqueConstraint("package_id", name="uq_incoming_packages_package_id"),
    )
    op.create_index(
        op.f("ix_incoming_packages_integrator_connection_id"),
        "incoming_packages",
        ["integrator_connection_id"],
        unique=False,
    )
    op.create_table(
        "incoming_package_versions",
        sa.Column("incoming_package_id", sa.Uuid(), nullable=False),
        sa.Column("package_id", sa.Uuid(), nullable=False),
        sa.Column("package_version", sa.Integer(), nullable=False),
        sa.Column("schema_version", sa.String(length=8), nullable=False),
        sa.Column("instance_id", sa.Uuid(), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("operation", sa.String(length=16), nullable=False),
        sa.Column("revision_reason", sa.Text(), nullable=True),
        sa.Column("body_sha256", sa.String(length=64), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "operation IN ('created', 'updated', 'corrected', 'retracted', 'deleted')",
            name=op.f("ck_incoming_package_versions_incoming_operation"),
        ),
        sa.CheckConstraint(
            "schema_version IN ('1.0', '1.1')",
            name=op.f("ck_incoming_package_versions_supported_schema_version"),
        ),
        sa.CheckConstraint(
            "package_version > 0",
            name=op.f("ck_incoming_package_versions_package_version_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["incoming_package_id"],
            ["incoming_packages.id"],
            name=op.f("fk_incoming_package_versions_incoming_package_id_incoming_packages"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_incoming_package_versions")),
        sa.UniqueConstraint("event_id", name="uq_incoming_package_versions_event_id"),
        sa.UniqueConstraint(
            "package_id", "package_version", name="uq_incoming_package_versions_identity"
        ),
    )
    op.create_index(
        op.f("ix_incoming_package_versions_incoming_package_id"),
        "incoming_package_versions",
        ["incoming_package_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_incoming_package_versions_instance_id"),
        "incoming_package_versions",
        ["instance_id"],
        unique=False,
    )
    op.create_index(
        "ix_incoming_package_versions_received_at",
        "incoming_package_versions",
        ["received_at"],
        unique=False,
    )
    op.add_column(
        "content_versions", sa.Column("incoming_package_version_id", sa.Uuid(), nullable=True)
    )
    op.create_unique_constraint(
        op.f("uq_content_versions_incoming_package_version_id"),
        "content_versions",
        ["incoming_package_version_id"],
    )
    op.create_foreign_key(
        op.f("fk_content_versions_incoming_package_version_id_incoming_package_versions"),
        "content_versions",
        "incoming_package_versions",
        ["incoming_package_version_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_content_versions_incoming_package_version_id_incoming_package_versions"),
        "content_versions",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("uq_content_versions_incoming_package_version_id"), "content_versions", type_="unique"
    )
    op.drop_column("content_versions", "incoming_package_version_id")
    op.drop_index(
        "ix_incoming_package_versions_received_at", table_name="incoming_package_versions"
    )
    op.drop_index(
        op.f("ix_incoming_package_versions_instance_id"), table_name="incoming_package_versions"
    )
    op.drop_index(
        op.f("ix_incoming_package_versions_incoming_package_id"),
        table_name="incoming_package_versions",
    )
    op.drop_table("incoming_package_versions")
    op.drop_index(
        op.f("ix_incoming_packages_integrator_connection_id"), table_name="incoming_packages"
    )
    op.drop_table("incoming_packages")
    op.drop_index(
        op.f("ix_integrator_connections_instance_id"), table_name="integrator_connections"
    )
    op.drop_table("integrator_connections")
    # ### end Alembic commands ###
