"""implement phase 3 editorial publication

Revision ID: 0004_phase_3_editorial
Revises: 0003_phase_2_ingestion
Create Date: 2026-08-30 16:08:16.818235
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0004_phase_3_editorial"
down_revision: str | None = "0003_phase_2_ingestion"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "editorial_audit_logs",
        sa.Column("actor", sa.String(length=255), nullable=False),
        sa.Column("action", sa.String(length=32), nullable=False),
        sa.Column("entity_type", sa.String(length=64), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("before", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("after", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "timestamp", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_editorial_audit_logs")),
    )
    op.create_index(
        "ix_editorial_audit_logs_entity",
        "editorial_audit_logs",
        ["entity_type", "entity_id"],
        unique=False,
    )
    op.create_index(
        "ix_editorial_audit_logs_timestamp", "editorial_audit_logs", ["timestamp"], unique=False
    )
    op.add_column(
        "content_items",
        sa.Column(
            "upstream_status",
            sa.Enum(
                "received",
                "processing",
                "ready",
                "scheduled",
                "published",
                "unpublished",
                "retracted",
                "archived",
                "deleted",
                "failed",
                name="content_status",
                native_enum=False,
            ),
            nullable=True,
        ),
    )
    op.execute("UPDATE content_items SET upstream_status = status")
    op.alter_column("content_items", "upstream_status", nullable=False)
    op.add_column(
        "content_items",
        sa.Column(
            "has_editorial_override", sa.Boolean(), server_default=sa.false(), nullable=False
        ),
    )
    op.add_column(
        "content_items", sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "content_items", sa.Column("site_published_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.create_index(
        "ix_content_items_scheduled_at", "content_items", ["scheduled_at"], unique=False
    )
    op.add_column(
        "content_versions",
        sa.Column("origin", sa.String(length=16), server_default="source", nullable=False),
    )
    op.create_check_constraint(
        op.f("ck_content_versions_content_version_origin"),
        "content_versions",
        "origin IN ('source', 'editorial')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("ck_content_versions_content_version_origin"), "content_versions", type_="check"
    )
    op.drop_column("content_versions", "origin")
    op.drop_index("ix_content_items_scheduled_at", table_name="content_items")
    op.drop_column("content_items", "site_published_at")
    op.drop_column("content_items", "scheduled_at")
    op.drop_column("content_items", "has_editorial_override")
    op.drop_column("content_items", "upstream_status")
    op.drop_index("ix_editorial_audit_logs_timestamp", table_name="editorial_audit_logs")
    op.drop_index("ix_editorial_audit_logs_entity", table_name="editorial_audit_logs")
    op.drop_table("editorial_audit_logs")
    # ### end Alembic commands ###
